/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tpcalculatrice;

/**
 *
 * @author KAPTUE PATRICE
 */
public class Tpcalcul extends javax.swing.JFrame {

    /**
     * Creates new form Tpcalcul
     */
    public Tpcalcul() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tnbre1 = new javax.swing.JTextField();
        Tnbre2 = new javax.swing.JTextField();
        Tresultat = new javax.swing.JTextField();
        Bquitter = new javax.swing.JButton();
        Bmodulo = new javax.swing.JButton();
        Bsoustraction = new javax.swing.JButton();
        Bdivision = new javax.swing.JButton();
        Baddition = new javax.swing.JButton();
        Bmultiplication = new javax.swing.JButton();
        Bannuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("nombre1");

        jLabel2.setText("nombre 2");

        jLabel3.setText("Resultat");

        Tresultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TresultatActionPerformed(evt);
            }
        });

        Bquitter.setText("Quitter");
        Bquitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BquitterActionPerformed(evt);
            }
        });

        Bmodulo.setText("%");
        Bmodulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmoduloActionPerformed(evt);
            }
        });

        Bsoustraction.setText("-");
        Bsoustraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsoustractionActionPerformed(evt);
            }
        });

        Bdivision.setText("/");
        Bdivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdivisionActionPerformed(evt);
            }
        });

        Baddition.setText("+");
        Baddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BadditionActionPerformed(evt);
            }
        });

        Bmultiplication.setText("*");
        Bmultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmultiplicationActionPerformed(evt);
            }
        });

        Bannuler.setText("Annuler");
        Bannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BannulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Tnbre1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tnbre2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tresultat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bquitter)
                        .addGap(44, 44, 44)
                        .addComponent(Bmodulo)))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bsoustraction)
                            .addComponent(Baddition)
                            .addComponent(Bmultiplication))
                        .addContainerGap(122, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bdivision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bannuler)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Tnbre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Baddition))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tnbre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Bsoustraction))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tresultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Bmultiplication))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bquitter)
                    .addComponent(Bmodulo)
                    .addComponent(Bdivision)
                    .addComponent(Bannuler))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BquitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BquitterActionPerformed
      System.exit(0);
    }//GEN-LAST:event_BquitterActionPerformed

    private void BsoustractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsoustractionActionPerformed
          String nbre1;
        String nbre2;
        
        nbre1= Tnbre1.getText();
        nbre2= Tnbre2.getText();
        
        int nbr1;
        int nbr2;
        
        int resultat= Integer.parseInt(nbre1) - Integer.parseInt(nbre2);
        String cResultat= String.valueOf(resultat);
        Tresultat.setText(cResultat);
        
    }//GEN-LAST:event_BsoustractionActionPerformed

    private void TresultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TresultatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TresultatActionPerformed

    private void BannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BannulerActionPerformed
        Tnbre1.setText("");
        Tnbre2.setText("");
    }//GEN-LAST:event_BannulerActionPerformed

    private void BadditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BadditionActionPerformed
        String nbre1;
        String nbre2;
        
        nbre1= Tnbre1.getText();
        nbre2= Tnbre2.getText();
        
        int nbr1;
        int nbr2;
        
        int resultat= Integer.parseInt(nbre1) + Integer.parseInt(nbre2);
        String cResultat= String.valueOf(resultat);
        Tresultat.setText(cResultat);
        
        
    }//GEN-LAST:event_BadditionActionPerformed

    private void BmultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmultiplicationActionPerformed
        String nbre1;
        String nbre2;
        
        nbre1= Tnbre1.getText();
        nbre2= Tnbre2.getText();
        
        int nbr1;
        int nbr2;
        
        int resultat= Integer.parseInt(nbre1) * Integer.parseInt(nbre2);
        String cResultat= String.valueOf(resultat);
        Tresultat.setText(cResultat);
        
    }//GEN-LAST:event_BmultiplicationActionPerformed

    private void BmoduloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmoduloActionPerformed
          String nbre1;
        String nbre2;
        
        nbre1= Tnbre1.getText();
        nbre2= Tnbre2.getText();
        
        int nbr1;
        int nbr2;
        
     int resultat= Integer.parseInt(nbre1) % Integer.parseInt(nbre2);
        String cResultat= String.valueOf(resultat);
        Tresultat.setText(cResultat);
        
    }//GEN-LAST:event_BmoduloActionPerformed

    private void BdivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdivisionActionPerformed
        String nbre1;
        String nbre2;
        
        nbre1= Tnbre1.getText();
        nbre2= Tnbre2.getText();
        
        int nbr1;
        int nbr2;
        
        int resultat= Integer.parseInt(nbre1) / Integer.parseInt(nbre2);
        String cResultat= String.valueOf(resultat);
        Tresultat.setText(cResultat);
    }//GEN-LAST:event_BdivisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tpcalcul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tpcalcul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tpcalcul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tpcalcul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tpcalcul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Baddition;
    private javax.swing.JButton Bannuler;
    private javax.swing.JButton Bdivision;
    private javax.swing.JButton Bmodulo;
    private javax.swing.JButton Bmultiplication;
    private javax.swing.JButton Bquitter;
    private javax.swing.JButton Bsoustraction;
    private javax.swing.JTextField Tnbre1;
    private javax.swing.JTextField Tnbre2;
    private javax.swing.JTextField Tresultat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
